name: Universal Controller
version: "1.4.0"
slug: universal_controller
description: Execute JavaScript/TypeScript code in Home Assistant with Monaco Editor
url: https://github.com/Nogg-aholic/UniControl
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
ports:
  8099/tcp: 8099
webui: http://[HOST]:[PORT:8099]
homeassistant_api: true
hassio_api: true
map:
  - share:rw
  - ssl
options:
  log_level: info
  port: 8099
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  port: port
  ssl: bool
  certfile: str?
  keyfile: str?
image: ghcr.io/nogg-aholic/{arch}-addon-universal-controller
